/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fish_farm;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.Border;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Nilma
 */
public class JFrame_10 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_10
     */
    public JFrame_10() {
        initComponents();
        showTableData();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        Border JPanel_title__Border = BorderFactory.createMatteBorder(7, 7, 7, 7, Color.black);
        jPanel1.setBorder(JPanel_title__Border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_Time = new javax.swing.JLabel();
        jLabel_Date = new javax.swing.JLabel();
        jTextField_Resource_ID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_Items = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Availability = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_Back = new javax.swing.JButton();
        jButton_Add = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jButton_Update = new javax.swing.JButton();
        jButton_New = new javax.swing.JButton();
        jButton_Search = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel_Check_ID = new javax.swing.JLabel();
        jLabel_Select_Item = new javax.swing.JLabel();
        jLabel_Select_Date = new javax.swing.JLabel();
        jLabel_Check_availability = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Resources  Details");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(904, 490));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        jPanel1.setPreferredSize(new java.awt.Dimension(897, 459));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Resources  Details");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 30, 890, 29);

        jLabel_Time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Time.setText("Time");
        jPanel1.add(jLabel_Time);
        jLabel_Time.setBounds(730, 90, 150, 30);

        jLabel_Date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Date.setText("Date");
        jPanel1.add(jLabel_Date);
        jLabel_Date.setBounds(20, 90, 180, 30);

        jTextField_Resource_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Resource_IDKeyReleased(evt);
            }
        });
        jPanel1.add(jTextField_Resource_ID);
        jTextField_Resource_ID.setBounds(180, 160, 220, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Resource ID :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 160, 100, 30);

        jComboBox_Items.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~Select Item~", "Tanks", "Moteres", "Pipes", "Fish Food", "Clorine" }));
        jComboBox_Items.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox_ItemsKeyReleased(evt);
            }
        });
        jPanel1.add(jComboBox_Items);
        jComboBox_Items.setBounds(180, 220, 220, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Availability :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 340, 110, 30);

        jTextField_Availability.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_AvailabilityKeyReleased(evt);
            }
        });
        jPanel1.add(jTextField_Availability);
        jTextField_Availability.setBounds(180, 340, 220, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Item :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 220, 150, 30);

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(430, 160, 440, 210);

        jButton_Back.setText("<<Back");
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Back);
        jButton_Back.setBounds(30, 410, 90, 30);

        jButton_Add.setText("Add");
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Add);
        jButton_Add.setBounds(190, 410, 90, 30);

        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Delete);
        jButton_Delete.setBounds(340, 410, 90, 30);

        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Update);
        jButton_Update.setBounds(490, 410, 90, 30);

        jButton_New.setText("New");
        jButton_New.setToolTipText("");
        jButton_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NewActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_New);
        jButton_New.setBounds(640, 410, 90, 30);

        jButton_Search.setText("Search");
        jButton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Search);
        jButton_Search.setBounds(790, 410, 90, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Date :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 280, 90, 30);

        jDateChooser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDateChooser1KeyReleased(evt);
            }
        });
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(180, 280, 220, 30);

        jLabel_Check_ID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Check_ID.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Check_ID);
        jLabel_Check_ID.setBounds(180, 190, 220, 30);

        jLabel_Select_Item.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Select_Item.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Select_Item);
        jLabel_Select_Item.setBounds(180, 250, 220, 30);

        jLabel_Select_Date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Select_Date.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Select_Date);
        jLabel_Select_Date.setBounds(180, 310, 220, 30);

        jLabel_Check_availability.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Check_availability.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Check_availability);
        jLabel_Check_availability.setBounds(180, 370, 220, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\My Works\\My Java Projects\\Fish_Farm\\Images\\page-background-default.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 880, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        Thread JFrame_10 = new Thread() {
            public void run() {
                for (;;) {
                    Calendar cal = new GregorianCalendar();
                    //Time:
                    int second = cal.get(Calendar.SECOND);
                    int minute = cal.get(Calendar.MINUTE);
                    int hour = cal.get(Calendar.HOUR);
                    //Date:
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    int month = cal.get(Calendar.MONTH);
                    int year = cal.get(Calendar.YEAR);

                    jLabel_Time.setText("Time :- " + hour + ":" + minute + ":" + second);
                    jLabel_Date.setText("Date :-" + " " + year + "-" + month + "-" + day);

                    try {
                        sleep(1000);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }
        };
        JFrame_10.start();

    }//GEN-LAST:event_formWindowOpened

    private void jTextField_Resource_IDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Resource_IDKeyReleased
        jLabel_Check_ID.setText(null);
    }//GEN-LAST:event_jTextField_Resource_IDKeyReleased

    private void jComboBox_ItemsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_ItemsKeyReleased
        jLabel_Select_Item.setText(null);
    }//GEN-LAST:event_jComboBox_ItemsKeyReleased

    private void jTextField_AvailabilityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_AvailabilityKeyReleased
        jLabel_Check_availability.setText(null);
    }//GEN-LAST:event_jTextField_AvailabilityKeyReleased

    private void jDateChooser1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser1KeyReleased
        jLabel_Select_Date.setText(null);
    }//GEN-LAST:event_jDateChooser1KeyReleased

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        JFrame_4 f4 = new JFrame_4();
        f4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed

        if (jTextField_Resource_ID.getText().trim().isEmpty() && jComboBox_Items.getSelectedItem().equals("~Select Item~") && jDateChooser1.getDate() == null && jTextField_Availability.getText().trim().isEmpty()) {

            getToolkit().beep();

            jLabel_Check_ID.setText("Enter the Resourse id number.");
            jLabel_Select_Item.setText("Selectthe item.");
            jLabel_Select_Date.setText("Select the Date.");
            jLabel_Check_availability.setText("Enter the Availability.");

        } else if (jTextField_Resource_ID.getText().trim().isEmpty()) {

            getToolkit().beep();
            jLabel_Check_ID.setText("Enter the Resourse id number.");

        } else if (jComboBox_Items.getSelectedItem().equals("~Select Item~")) {

            getToolkit().beep();
            jLabel_Select_Item.setText("Selectthe item.");

        } else if (jDateChooser1.getDate() == null) {

            getToolkit().beep();
            jLabel_Select_Date.setText("Select the Date.");

        } else if (jTextField_Availability.getText().trim().isEmpty()) {

            getToolkit().beep();
            jLabel_Check_availability.setText("Enter the Availability.");

        } else {

            try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/";
                String db = "fishing_management_system";
                String user = "root";
                String pword = "123456";

                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);

                String query = "INSERT INTO resources_details(Resource_ID, Item, Date, Availability)VALUES(?,?,?,?)";

                PreparedStatement pst = con.prepareStatement(query);

                pst.setString(1, jTextField_Resource_ID.getText());
                pst.setString(2, jComboBox_Items.getSelectedItem().toString());

                SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
                String date1 = sdf1.format(jDateChooser1.getDate());
                pst.setString(3, date1);
                pst.setString(4, jTextField_Availability.getText());

                pst.executeUpdate();

                System.out.println(pst);
                System.out.println("1 row affected.");
                JOptionPane.showMessageDialog(null, "Record Added Succsessfully...");

                con.close();

            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {

                Logger.getLogger(JFrame_10.class.getName()).log(Level.SEVERE, null, ex);
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, ex);

                jTextField_Resource_ID.setText(null);
                jComboBox_Items.setSelectedItem("~Select Item~");
                jDateChooser1.setDate(null);
                jTextField_Availability.setText(null);
                jLabel_Check_ID.setText(null);
                jLabel_Check_availability.setText(null);
                jLabel_Select_Date.setText(null);
                jLabel_Select_Item.setText(null);
                jTextField_Resource_ID.grabFocus();
            }

        }

        showTableData();
    }//GEN-LAST:event_jButton_AddActionPerformed

    private void jButton_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NewActionPerformed

        int a;
        getToolkit().beep();
        a = a = JOptionPane.showConfirmDialog(null, "Are you sure to you save that data into the database?", "Go to new form.", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (a == 0) {

            jTextField_Resource_ID.setText(null);
            jComboBox_Items.setSelectedItem("~Select Item~");
            jDateChooser1.setDate(null);
            jTextField_Availability.setText(null);
            jLabel_Check_ID.setText(null);
            jLabel_Check_availability.setText(null);
            jLabel_Select_Date.setText(null);
            jLabel_Select_Item.setText(null);
            jTextField_Resource_ID.grabFocus();

        }
    }//GEN-LAST:event_jButton_NewActionPerformed

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed

        if (jTextField_Resource_ID.getText().trim().isEmpty() && jComboBox_Items.getSelectedItem().equals("~Select Item~") && jDateChooser1.getDate() == null && jTextField_Availability.getText().trim().isEmpty()) {

            getToolkit().beep();

            jLabel_Check_ID.setText("Enter the Resourse id number.");
            jLabel_Select_Item.setText("Selectthe item.");
            jLabel_Select_Date.setText("Select the Date.");
            jLabel_Check_availability.setText("Enter the Availability.");

        } else if (jTextField_Resource_ID.getText().trim().isEmpty()) {

            getToolkit().beep();
            jLabel_Check_ID.setText("Enter the Resourse id number.");

        } else if (jComboBox_Items.getSelectedItem().equals("~Select Item~")) {

            getToolkit().beep();
            jLabel_Select_Item.setText("Selectthe item.");

        } else if (jDateChooser1.getDate() == null) {

            getToolkit().beep();
            jLabel_Select_Date.setText("Select the Date.");

        } else if (jTextField_Availability.getText().trim().isEmpty()) {

            getToolkit().beep();
            jLabel_Check_availability.setText("Enter the Availability.");

        } else {

            try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/";
                String db = "fishing_management_system";
                String user = "root";
                String pword = "123456";

                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);

                String Query = "UPDATE resources_details SET Item=? ,Date=? ,Availability=? WHERE Resource_ID=?";

                PreparedStatement pst = con.prepareStatement(Query);

                pst.setString(4, jTextField_Resource_ID.getText());
                pst.setString(1, jComboBox_Items.getSelectedItem().toString());

                SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
                String date1 = sdf1.format(jDateChooser1.getDate());
                pst.setString(2, date1);
                pst.setString(3, jTextField_Availability.getText());

                pst.executeUpdate();

                jTextField_Resource_ID.setText(null);
                jComboBox_Items.setSelectedItem("~Select Item~");
                jDateChooser1.setDate(null);
                jTextField_Availability.setText(null);
                jLabel_Check_ID.setText(null);
                jLabel_Check_availability.setText(null);
                jLabel_Select_Date.setText(null);
                jLabel_Select_Item.setText(null);
                jTextField_Resource_ID.grabFocus();

                System.out.println(pst);
                System.out.println("1 row updated...");

                JOptionPane.showMessageDialog(null, "Record Update Succsessftlly...");

                con.close();

            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {

                Logger.getLogger(JFrame_9.class.getName()).log(Level.SEVERE, null, ex);
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, ex);

                jTextField_Resource_ID.setText(null);
                jComboBox_Items.setSelectedItem("~Select Item~");
                jDateChooser1.setDate(null);
                jTextField_Availability.setText(null);
                jLabel_Check_ID.setText(null);
                jLabel_Check_availability.setText(null);
                jLabel_Select_Date.setText(null);
                jLabel_Select_Item.setText(null);
                jTextField_Resource_ID.grabFocus();
            }

        }

        showTableData();
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed

        if (jTextField_Resource_ID.getText().trim().isEmpty()) {

            getToolkit().beep();
            jLabel_Check_ID.setText("Enter the reource ID.");

        } else {

            try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/";
                String db = "fishing_management_system";
                String user = "root";
                String pword = "123456";

                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);

                String query = "DELETE FROM resources_details WHERE Resource_ID=?";

                PreparedStatement pst = con.prepareStatement(query);

                pst.setString(1, jTextField_Resource_ID.getText());
                pst.executeUpdate();

                jTextField_Resource_ID.setText(null);
                jComboBox_Items.setSelectedItem("~Select Item~");
                jDateChooser1.setDate(null);
                jTextField_Availability.setText(null);
                jLabel_Check_ID.setText(null);
                jLabel_Check_availability.setText(null);
                jLabel_Select_Date.setText(null);
                jLabel_Select_Item.setText(null);
                jTextField_Resource_ID.grabFocus();

                System.out.println(pst);
                System.out.println("1 row deleted...");

                JOptionPane.showMessageDialog(null, "Record Deleted Succsessftlly...");

                con.close();

            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {

                Logger.getLogger(JFrame_9.class.getName()).log(Level.SEVERE, null, ex);
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, ex);

                jTextField_Resource_ID.setText(null);
                jComboBox_Items.setSelectedItem("~Select Item~");
                jDateChooser1.setDate(null);
                jTextField_Availability.setText(null);
                jLabel_Check_ID.setText(null);
                jLabel_Check_availability.setText(null);
                jLabel_Select_Date.setText(null);
                jLabel_Select_Item.setText(null);
                jTextField_Resource_ID.grabFocus();
            }

        }
        showTableData();
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchActionPerformed

        if (jTextField_Resource_ID.getText().trim().isEmpty()) {

            getToolkit().beep();
            jLabel_Check_ID.setText("Enter the reource ID.");

        } else {

            try {

                String url = "jdbc:mysql://localhost:3306/";
                String db = "fishing_management_system";
                String user = "root";
                String pword = "123456";

                System.out.println(jTextField_Resource_ID.getText());
                Connection con = null;
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance(); //driver
                con = DriverManager.getConnection(url + db, user, pword);

                String query = "SELECT * FROM resources_details WHERE Resource_ID = '" + jTextField_Resource_ID.getText() + "'";

                ResultSet res = con.createStatement().executeQuery(query);
                System.out.println(query);

                while (res.next()) {

                    jComboBox_Items.setSelectedItem(res.getString("Item"));
                    jDateChooser1.setDate(res.getDate("Date"));
                    jTextField_Availability.setText(res.getString("Availability"));

                    System.out.println(res.getString("Item") + " " + res.getString("Availability"));
                    System.out.println("Row Affected");

                }

                con.close();

            } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex) {

                Logger.getLogger(JFrame_8.class.getName()).log(Level.SEVERE, null, ex);
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, ex);

                jTextField_Resource_ID.setText(null);
                jComboBox_Items.setSelectedItem("~Select Item~");
                jDateChooser1.setDate(null);
                jTextField_Availability.setText(null);
                jLabel_Check_ID.setText(null);
                jLabel_Check_availability.setText(null);
                jLabel_Select_Date.setText(null);
                jLabel_Select_Item.setText(null);
                jTextField_Resource_ID.grabFocus();

            }

        }
        showTableData();
    }//GEN-LAST:event_jButton_SearchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int rows = jTable1.getRowCount();
        if (rows != 0) {

            int row_selected = jTable1.getSelectedRow();

            String Resourse_ID = jTable1.getValueAt(row_selected, 0).toString();
            String Item = jTable1.getValueAt(row_selected, 1).toString();
            Object Date = jTable1.getValueAt(row_selected, 2);
            String Availability = jTable1.getValueAt(row_selected, 3).toString();

            jTextField_Resource_ID.setText(Resourse_ID);
            jComboBox_Items.setSelectedItem(Item);
            jDateChooser1.setDate((java.util.Date) Date);
            jTextField_Availability.setText(Availability);

        } else {

            JOptionPane.showMessageDialog(null, rows);
        }


    }//GEN-LAST:event_jTable1MouseClicked

    public void showTableData() {

        try {

            String url = "jdbc:mysql://localhost:3306/";
            String db = "fishing_management_system";
            String user = "root";
            String pword = "123456";

            Connection con = null;
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            con = DriverManager.getConnection(url + db, user, pword);

            String queary = "SELECT * FROM resources_details;";

            PreparedStatement pst = con.prepareStatement(queary);
            ResultSet res = con.createStatement().executeQuery(queary);
            pst = con.prepareStatement(queary);

            res = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(res));

        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex) {

            Logger.getLogger(JFrame_8.class.getName()).log(Level.SEVERE, null, ex);
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, ex);

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;*/
                UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");

            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_New;
    private javax.swing.JButton jButton_Search;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JComboBox<String> jComboBox_Items;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Check_ID;
    private javax.swing.JLabel jLabel_Check_availability;
    private javax.swing.JLabel jLabel_Date;
    private javax.swing.JLabel jLabel_Select_Date;
    private javax.swing.JLabel jLabel_Select_Item;
    private javax.swing.JLabel jLabel_Time;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_Availability;
    private javax.swing.JTextField jTextField_Resource_ID;
    // End of variables declaration//GEN-END:variables
}
