/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fish_farm;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.Border;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Nilma
 */
public class JFrame_9 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_9
     */
    public JFrame_9() {
        initComponents();
        showTableData();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        Border JPanel_title__Border = BorderFactory.createMatteBorder(7, 7, 7, 7, Color.black);
        jPanel1.setBorder(JPanel_title__Border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Date = new javax.swing.JLabel();
        jLabel_Time = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Tel_No = new javax.swing.JTextField();
        jTextField_Customer_ID1 = new javax.swing.JTextField();
        jTextField_Customer_Name1 = new javax.swing.JTextField();
        jTextField_Quantity1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_Delete = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();
        jButton_Add = new javax.swing.JButton();
        jLabel_Check_Date = new javax.swing.JLabel();
        jButton_Update = new javax.swing.JButton();
        jButton_New = new javax.swing.JButton();
        jButton_Search = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel_Check_ID = new javax.swing.JLabel();
        jLabel_Check_Name = new javax.swing.JLabel();
        jLabel_Check_Quality = new javax.swing.JLabel();
        jLabel_Check_Tel_no = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_customer_Type = new javax.swing.JComboBox<>();
        jLabel_Check_Customer_Type = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_Ammount1 = new javax.swing.JTextField();
        jLabel_Check_Ammount1 = new javax.swing.JLabel();
        jButton_Open_Cal = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer  Details");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        jPanel1.setLayout(null);

        jLabel_Date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Date.setText("Date");
        jPanel1.add(jLabel_Date);
        jLabel_Date.setBounds(20, 90, 180, 30);

        jLabel_Time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Time.setText("Time");
        jPanel1.add(jLabel_Time);
        jLabel_Time.setBounds(730, 100, 150, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Customer  Details");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 30, 900, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Customer Type :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 230, 120, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Customer Name :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 290, 130, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Quantity :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 350, 80, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Telephone No  :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 530, 120, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Date :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 470, 110, 20);

        jTextField_Tel_No.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Tel_NoKeyReleased(evt);
            }
        });
        jPanel1.add(jTextField_Tel_No);
        jTextField_Tel_No.setBounds(170, 530, 220, 30);

        jTextField_Customer_ID1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Customer_ID1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField_Customer_ID1);
        jTextField_Customer_ID1.setBounds(170, 170, 220, 30);

        jTextField_Customer_Name1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Customer_Name1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField_Customer_Name1);
        jTextField_Customer_Name1.setBounds(170, 290, 220, 30);

        jTextField_Quantity1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Quantity1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField_Quantity1);
        jTextField_Quantity1.setBounds(170, 350, 220, 30);

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(450, 170, 420, 260);

        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Delete);
        jButton_Delete.setBounds(320, 600, 90, 30);

        jButton_Back.setText("<<Back");
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Back);
        jButton_Back.setBounds(40, 600, 90, 30);

        jButton_Add.setText("Add");
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Add);
        jButton_Add.setBounds(180, 600, 90, 30);

        jLabel_Check_Date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Check_Date.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Check_Date);
        jLabel_Check_Date.setBounds(170, 500, 220, 30);

        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Update);
        jButton_Update.setBounds(480, 600, 90, 30);

        jButton_New.setText("New");
        jButton_New.setToolTipText("");
        jButton_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NewActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_New);
        jButton_New.setBounds(640, 600, 90, 30);

        jButton_Search.setText("Search");
        jButton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Search);
        jButton_Search.setBounds(790, 600, 90, 30);

        jDateChooser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDateChooser1KeyReleased(evt);
            }
        });
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(170, 470, 220, 30);

        jLabel_Check_ID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Check_ID.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Check_ID);
        jLabel_Check_ID.setBounds(170, 200, 220, 30);

        jLabel_Check_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Check_Name.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Check_Name);
        jLabel_Check_Name.setBounds(170, 320, 220, 30);

        jLabel_Check_Quality.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Check_Quality.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Check_Quality);
        jLabel_Check_Quality.setBounds(170, 380, 220, 30);

        jLabel_Check_Tel_no.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Check_Tel_no.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Check_Tel_no);
        jLabel_Check_Tel_no.setBounds(170, 560, 220, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Customer ID :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 170, 100, 20);

        jComboBox_customer_Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~Select Customer Type~", "Wholesaleres", "Retaileres" }));
        jComboBox_customer_Type.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_customer_TypeItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox_customer_Type);
        jComboBox_customer_Type.setBounds(170, 230, 220, 30);

        jLabel_Check_Customer_Type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Check_Customer_Type.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Check_Customer_Type);
        jLabel_Check_Customer_Type.setBounds(170, 260, 220, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Open the Calculator");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(580, 480, 200, 30);

        jTextField_Ammount1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Ammount1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField_Ammount1);
        jTextField_Ammount1.setBounds(170, 410, 220, 30);

        jLabel_Check_Ammount1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Check_Ammount1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Check_Ammount1);
        jLabel_Check_Ammount1.setBounds(170, 440, 220, 30);

        jButton_Open_Cal.setIcon(new javax.swing.ImageIcon("D:\\My Works\\My Java Projects\\Fish_Farm\\Images\\calculator.png")); // NOI18N
        jButton_Open_Cal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Open_Cal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Open_Cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Open_CalActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Open_Cal);
        jButton_Open_Cal.setBounds(450, 450, 100, 120);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Amount Paid :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 410, 100, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\My Works\\My Java Projects\\Fish_Farm\\Images\\g5AQGj.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 880, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        Thread JFrame_9 = new Thread() {
            public void run() {
                for (;;) {
                    Calendar cal = new GregorianCalendar();
                    //Time:
                    int second = cal.get(Calendar.SECOND);
                    int minute = cal.get(Calendar.MINUTE);
                    int hour = cal.get(Calendar.HOUR);
                    //Date:
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    int month = cal.get(Calendar.MONTH);
                    int year = cal.get(Calendar.YEAR);

                    jLabel_Time.setText("Time :- " + hour + ":" + minute + ":" + second);
                    jLabel_Date.setText("Date :-" + " " + year + "-" + month + "-" + day);

                    try {
                        sleep(1000);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }
        };
        JFrame_9.start();

    }//GEN-LAST:event_formWindowOpened

    private void jTextField_Tel_NoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Tel_NoKeyReleased
        jLabel_Check_Tel_no.setText(null);
    }//GEN-LAST:event_jTextField_Tel_NoKeyReleased

    private void jTextField_Customer_ID1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Customer_ID1KeyReleased
        jLabel_Check_ID.setText(null);
    }//GEN-LAST:event_jTextField_Customer_ID1KeyReleased

    private void jTextField_Customer_Name1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Customer_Name1KeyReleased
        jLabel_Check_Name.setText(null);
    }//GEN-LAST:event_jTextField_Customer_Name1KeyReleased

    private void jTextField_Quantity1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Quantity1KeyReleased
        jLabel_Check_Quality.setText(null);
    }//GEN-LAST:event_jTextField_Quantity1KeyReleased

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        JFrame_4 f4 = new JFrame_4();
        f4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jTextField_Ammount1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Ammount1KeyReleased
        jLabel_Check_Ammount1.setText(null);
    }//GEN-LAST:event_jTextField_Ammount1KeyReleased

    private void jComboBox_customer_TypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_customer_TypeItemStateChanged
        jLabel_Check_Customer_Type.setText(null);
    }//GEN-LAST:event_jComboBox_customer_TypeItemStateChanged

    private void jButton_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NewActionPerformed

        int a;
        getToolkit().beep();
        a = a = JOptionPane.showConfirmDialog(null, "Are you sure to you save that data into the database?", "Go to new form.", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (a == 0) {

            jTextField_Customer_ID1.setText(null);
            jComboBox_customer_Type.setSelectedItem("~Select Customer Type~");
            jTextField_Customer_Name1.setText(null);
            jTextField_Quantity1.setText(null);
            jTextField_Ammount1.setText(null);
            jDateChooser1.setDate(null);
            jTextField_Tel_No.setText(null);
            jLabel_Check_ID.setText(null);
            jLabel_Check_Customer_Type.setText(null);
            jLabel_Check_Name.setText(null);
            jLabel_Check_Quality.setText(null);
            jLabel_Check_Ammount1.setText(null);
            jLabel_Check_Date.setText(null);
            jLabel_Check_Tel_no.setText(null);
            jTextField_Customer_ID1.grabFocus();

        }

    }//GEN-LAST:event_jButton_NewActionPerformed

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed

        if (jTextField_Customer_ID1.getText().trim().isEmpty() && jComboBox_customer_Type.getSelectedItem().equals("~Select Customer Type~") && jTextField_Customer_Name1.getText().trim().isEmpty() && jTextField_Quantity1.getText().trim().isEmpty() && jTextField_Ammount1.getText().trim().isEmpty() && jDateChooser1.getDate() == null && jTextField_Tel_No.getText().trim().isEmpty()) {

            getToolkit().beep();

            jLabel_Check_ID.setText("Enter the Customer id number.");
            jLabel_Check_Customer_Type.setText("Select Customer type.");
            jLabel_Check_Name.setText("Enter the Customer name.");
            jLabel_Check_Quality.setText("Enter the Quantity.");
            jLabel_Check_Ammount1.setText("Enter the Ammount.");
            jLabel_Check_Date.setText("Enter the Date.");
            jLabel_Check_Tel_no.setText("Enter the telephone number.");

        } else if (jTextField_Customer_ID1.getText().trim().isEmpty()) {

            getToolkit().beep();
            jLabel_Check_ID.setText("Enter the Customer id number.");

        } else if (jComboBox_customer_Type.getSelectedItem().equals("~Select Customer Type~")) {

            getToolkit().beep();
            jLabel_Check_Customer_Type.setText("Select Customer type.");

        } else if (jTextField_Customer_Name1.getText().trim().isEmpty()) {

            getToolkit().beep();
            jLabel_Check_Name.setText("Enter the Customer name.");

        } else if (jTextField_Quantity1.getText().trim().isEmpty()) {

            getToolkit().beep();
            jLabel_Check_Quality.setText("Enter the Quantity.");

        } else if (jTextField_Ammount1.getText().trim().isEmpty()) {

            getToolkit().beep();
            jLabel_Check_Ammount1.setText("Enter the Ammount.");

        } else if (jDateChooser1.getDate() == null) {

            getToolkit().beep();
            jLabel_Check_Date.setText("Eter the date.");

        } else if (jTextField_Tel_No.getText().trim().isEmpty()) {

            getToolkit().beep();
            jLabel_Check_Tel_no.setText("Enter the Telephone No.");

        } else {

            try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/";
                String db = "fishing_management_system";
                String user = "root";
                String pword = "123456";

                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);

                String query = "INSERT INTO customer_details(Customer_ID, Customer_Type, Customer_Name, Quantity, Amount_Paid, Date, Telephone_Number)VALUES(?,?,?,?,?,?,?)";

                PreparedStatement pst = con.prepareStatement(query);

                pst.setString(1, jTextField_Customer_ID1.getText());
                pst.setString(2, jComboBox_customer_Type.getSelectedItem().toString());
                pst.setString(3, jTextField_Customer_Name1.getText());
                pst.setString(4, jTextField_Quantity1.getText());
                pst.setString(5, jTextField_Ammount1.getText());

                SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
                String date1 = sdf1.format(jDateChooser1.getDate());
                pst.setString(6, date1);
                pst.setString(7, jTextField_Tel_No.getText());

                pst.executeUpdate();

                System.out.println(pst);
                System.out.println("1 row affected.");
                JOptionPane.showMessageDialog(null, "Record Added Succsessfully...");

                con.close();

            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {

                Logger.getLogger(JFrame_9.class.getName()).log(Level.SEVERE, null, ex);
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, ex);

                jTextField_Customer_ID1.setText(null);
                jComboBox_customer_Type.setSelectedItem("~Select Customer Type~");
                jTextField_Customer_Name1.setText(null);
                jTextField_Quantity1.setText(null);
                jTextField_Ammount1.setText(null);
                jDateChooser1.setDate(null);
                jTextField_Tel_No.setText(null);
                jLabel_Check_ID.setText(null);
                jLabel_Check_Customer_Type.setText(null);
                jLabel_Check_Name.setText(null);
                jLabel_Check_Quality.setText(null);
                jLabel_Check_Ammount1.setText(null);
                jLabel_Check_Date.setText(null);
                jLabel_Check_Tel_no.setText(null);
                jTextField_Customer_ID1.grabFocus();
            }

        }
        showTableData();
    }//GEN-LAST:event_jButton_AddActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed

        if (jTextField_Customer_ID1.getText().trim().isEmpty()) {

            getToolkit().beep();
            jLabel_Check_ID.setText("Enter the Customer id number");

        } else {

            try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/";
                String db = "fishing_management_system";
                String user = "root";
                String pword = "123456";

                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);

                String query = "DELETE FROM customer_details WHERE Customer_ID=?";

                PreparedStatement pst = con.prepareStatement(query);

                pst.setString(1, jTextField_Customer_ID1.getText());
                pst.executeUpdate();

                jTextField_Customer_ID1.setText(null);
                jComboBox_customer_Type.setSelectedItem("~Select Customer Type~");
                jTextField_Customer_Name1.setText(null);
                jTextField_Quantity1.setText(null);
                jTextField_Ammount1.setText(null);
                jDateChooser1.setDate(null);
                jTextField_Tel_No.setText(null);
                jLabel_Check_ID.setText(null);
                jLabel_Check_Customer_Type.setText(null);
                jLabel_Check_Name.setText(null);
                jLabel_Check_Quality.setText(null);
                jLabel_Check_Ammount1.setText(null);
                jLabel_Check_Date.setText(null);
                jLabel_Check_Tel_no.setText(null);
                jTextField_Customer_ID1.grabFocus();

                System.out.println(pst);
                System.out.println("1 row deleted...");

                JOptionPane.showMessageDialog(null, "Record Deleted Succsessftlly...");

                con.close();

            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {

                Logger.getLogger(JFrame_9.class.getName()).log(Level.SEVERE, null, ex);
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, ex);

                jTextField_Customer_ID1.setText(null);
                jComboBox_customer_Type.setSelectedItem("~Select Customer Type~");
                jTextField_Customer_Name1.setText(null);
                jTextField_Quantity1.setText(null);
                jTextField_Ammount1.setText(null);
                jDateChooser1.setDate(null);
                jTextField_Tel_No.setText(null);
                jLabel_Check_ID.setText(null);
                jLabel_Check_Customer_Type.setText(null);
                jLabel_Check_Name.setText(null);
                jLabel_Check_Quality.setText(null);
                jLabel_Check_Ammount1.setText(null);
                jLabel_Check_Date.setText(null);
                jLabel_Check_Tel_no.setText(null);
                jTextField_Customer_ID1.grabFocus();
            }
        }

        showTableData();
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        if (jTextField_Customer_ID1.getText().trim().isEmpty() && jComboBox_customer_Type.getSelectedItem().equals("~Select Customer Type~") && jTextField_Customer_Name1.getText().trim().isEmpty() && jTextField_Quantity1.getText().trim().isEmpty() && jTextField_Ammount1.getText().trim().isEmpty() && jDateChooser1.getDate() == null && jTextField_Tel_No.getText().trim().isEmpty()) {

            getToolkit().beep();

            jLabel_Check_ID.setText("Enter the Customer id number.");
            jLabel_Check_Customer_Type.setText("Select Customer type.");
            jLabel_Check_Name.setText("Enter the Customer name.");
            jLabel_Check_Quality.setText("Enter the Quantity.");
            jLabel_Check_Ammount1.setText("Enter the Ammount.");
            jLabel_Check_Date.setText("Enter the Date.");
            jLabel_Check_Tel_no.setText("Enter the telephone number.");

        } else if (jTextField_Customer_ID1.getText().trim().isEmpty()) {

            getToolkit().beep();
            jLabel_Check_ID.setText("Enter the Customer id number.");

        } else if (jComboBox_customer_Type.getSelectedItem().equals("~Select Customer Type~")) {

            getToolkit().beep();
            jLabel_Check_Customer_Type.setText("Select Customer type.");

        } else if (jTextField_Customer_Name1.getText().trim().isEmpty()) {

            getToolkit().beep();
            jLabel_Check_Name.setText("Enter the Customer name.");

        } else if (jTextField_Quantity1.getText().trim().isEmpty()) {

            getToolkit().beep();
            jLabel_Check_Quality.setText("Enter the Quantity.");

        } else if (jTextField_Ammount1.getText().trim().isEmpty()) {

            getToolkit().beep();
            jLabel_Check_Ammount1.setText("Enter the Ammount.");

        } else if (jDateChooser1.getDate() == null) {

            getToolkit().beep();
            jLabel_Check_Date.setText("Eter the date.");

        } else if (jTextField_Tel_No.getText().trim().isEmpty()) {

            getToolkit().beep();
            jLabel_Check_Tel_no.setText("Enter the Telephone No.");

        } else {

            try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/";
                String db = "fishing_management_system";
                String user = "root";
                String pword = "123456";

                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);

                String Query = "UPDATE customer_details SET Customer_Type=? ,Customer_Name=? ,Quantity=? ,Amount_Paid=? ,Date=? ,Telephone_Number=?  WHERE Customer_ID=?";

                PreparedStatement pst = con.prepareStatement(Query);

                pst.setString(7, jTextField_Customer_ID1.getText());
                pst.setString(1, jComboBox_customer_Type.getSelectedItem().toString());
                pst.setString(2, jTextField_Customer_Name1.getText());
                pst.setString(3, jTextField_Quantity1.getText());
                pst.setString(4, jTextField_Ammount1.getText());

                SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
                String date1 = sdf1.format(jDateChooser1.getDate());
                pst.setString(5, date1);
                pst.setString(6, jTextField_Tel_No.getText());

                pst.executeUpdate();

                jTextField_Customer_ID1.setText(null);
                jComboBox_customer_Type.setSelectedItem("~Select Customer Type~");
                jTextField_Customer_Name1.setText(null);
                jTextField_Quantity1.setText(null);
                jTextField_Ammount1.setText(null);
                jDateChooser1.setDate(null);
                jTextField_Tel_No.setText(null);
                jLabel_Check_ID.setText(null);
                jLabel_Check_Customer_Type.setText(null);
                jLabel_Check_Name.setText(null);
                jLabel_Check_Quality.setText(null);
                jLabel_Check_Ammount1.setText(null);
                jLabel_Check_Date.setText(null);
                jLabel_Check_Tel_no.setText(null);
                jTextField_Customer_ID1.grabFocus();

                System.out.println(pst);
                System.out.println("1 row updated...");

                JOptionPane.showMessageDialog(null, "Record Update Succsessftlly...");

                con.close();

            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {

                Logger.getLogger(JFrame_9.class.getName()).log(Level.SEVERE, null, ex);
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, ex);

                jTextField_Customer_ID1.setText(null);
                jComboBox_customer_Type.setSelectedItem("~Select Customer Type~");
                jTextField_Customer_Name1.setText(null);
                jTextField_Quantity1.setText(null);
                jTextField_Ammount1.setText(null);
                jDateChooser1.setDate(null);
                jTextField_Tel_No.setText(null);
                jLabel_Check_ID.setText(null);
                jLabel_Check_Customer_Type.setText(null);
                jLabel_Check_Name.setText(null);
                jLabel_Check_Quality.setText(null);
                jLabel_Check_Ammount1.setText(null);
                jLabel_Check_Date.setText(null);
                jLabel_Check_Tel_no.setText(null);
                jTextField_Customer_ID1.grabFocus();
            }

        }

        showTableData();
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jDateChooser1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser1KeyReleased
        jLabel_Check_Date.setText(null);
    }//GEN-LAST:event_jDateChooser1KeyReleased

    private void jButton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchActionPerformed

        if (jTextField_Customer_ID1.getText().trim().isEmpty()) {

            getToolkit().beep();
            jLabel_Check_ID.setText("Enter the Customer id number");

        } else {

            try {

                String url = "jdbc:mysql://localhost:3306/";
                String db = "fishing_management_system";
                String user = "root";
                String pword = "123456";

                System.out.println(jTextField_Customer_ID1.getText());
                Connection con = null;
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance(); //driver
                con = DriverManager.getConnection(url + db, user, pword);

                String query = "SELECT * FROM customer_details WHERE Customer_ID = '" + jTextField_Customer_ID1.getText() + "'";

                ResultSet res = con.createStatement().executeQuery(query);
                System.out.println(query);

                while (res.next()) {

                    jComboBox_customer_Type.setSelectedItem(res.getString("Customer_Type"));
                    jTextField_Customer_Name1.setText(res.getString("Customer_Name"));
                    jTextField_Quantity1.setText(res.getString("Quantity"));
                    jTextField_Ammount1.setText(res.getString("Amount_Paid"));
                    jDateChooser1.setDate(res.getDate("Date"));
                    jTextField_Tel_No.setText(res.getString("Telephone_Number"));

                    System.out.println(res.getString("Customer_Name") + " " + res.getString("Quantity"));
                    System.out.println("Row Affected");

                }

                con.close();

            } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex) {

                Logger.getLogger(JFrame_8.class.getName()).log(Level.SEVERE, null, ex);
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, ex);

                jTextField_Customer_ID1.setText(null);
                jComboBox_customer_Type.setSelectedItem("~Select Customer Type~");
                jTextField_Customer_Name1.setText(null);
                jTextField_Quantity1.setText(null);
                jTextField_Ammount1.setText(null);
                jDateChooser1.setDate(null);
                jTextField_Tel_No.setText(null);
                jLabel_Check_ID.setText(null);
                jLabel_Check_Customer_Type.setText(null);
                jLabel_Check_Name.setText(null);
                jLabel_Check_Quality.setText(null);
                jLabel_Check_Ammount1.setText(null);
                jLabel_Check_Date.setText(null);
                jLabel_Check_Tel_no.setText(null);
                jTextField_Customer_ID1.grabFocus();
            }

        }

        showTableData();
    }//GEN-LAST:event_jButton_SearchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int rows = jTable1.getRowCount();
        if (rows != 0) {

            int row_selected = jTable1.getSelectedRow();

            String Customer_ID = jTable1.getValueAt(row_selected, 0).toString();
            String Select_Customer = jTable1.getValueAt(row_selected, 1).toString();
            String Customer_name = jTable1.getValueAt(row_selected, 2).toString();
            String Quntity = jTable1.getValueAt(row_selected, 3).toString();
            String Amount_Paid = jTable1.getValueAt(row_selected, 4).toString();
            Object jDateChooser_Date = jTable1.getValueAt(row_selected, 5);
            String Tel_No = jTable1.getValueAt(row_selected, 6).toString();

            jTextField_Customer_ID1.setText(Customer_ID);
            jComboBox_customer_Type.setSelectedItem(Select_Customer);
            jTextField_Customer_Name1.setText(Customer_name);
            jTextField_Quantity1.setText(Quntity);
            jTextField_Ammount1.setText(Amount_Paid);
            jDateChooser1.setDate((java.util.Date) jDateChooser_Date);
            jTextField_Tel_No.setText(Tel_No);

        } else {

            JOptionPane.showMessageDialog(null, rows);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_Open_CalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Open_CalActionPerformed
        JFrame_12 f12 = new JFrame_12();
        f12.setVisible(true);
    }//GEN-LAST:event_jButton_Open_CalActionPerformed

    public void showTableData() {

        try {

            String url = "jdbc:mysql://localhost:3306/";
            String db = "fishing_management_system";
            String user = "root";
            String pword = "123456";

            Connection con = null;
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            con = DriverManager.getConnection(url + db, user, pword);

            String queary = "SELECT * FROM customer_details;";

            PreparedStatement pst = con.prepareStatement(queary);
            ResultSet res = con.createStatement().executeQuery(queary);
            pst = con.prepareStatement(queary);

            res = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(res));

        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex) {

            Logger.getLogger(JFrame_9.class.getName()).log(Level.SEVERE, null, ex);
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, ex);

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;*/
                UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_New;
    private javax.swing.JButton jButton_Open_Cal;
    private javax.swing.JButton jButton_Search;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JComboBox<String> jComboBox_customer_Type;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Check_Ammount1;
    private javax.swing.JLabel jLabel_Check_Customer_Type;
    private javax.swing.JLabel jLabel_Check_Date;
    private javax.swing.JLabel jLabel_Check_ID;
    private javax.swing.JLabel jLabel_Check_Name;
    private javax.swing.JLabel jLabel_Check_Quality;
    private javax.swing.JLabel jLabel_Check_Tel_no;
    private javax.swing.JLabel jLabel_Date;
    private javax.swing.JLabel jLabel_Time;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_Ammount1;
    private javax.swing.JTextField jTextField_Customer_ID1;
    private javax.swing.JTextField jTextField_Customer_Name1;
    private javax.swing.JTextField jTextField_Quantity1;
    private javax.swing.JTextField jTextField_Tel_No;
    // End of variables declaration//GEN-END:variables
}
