/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fish_farm;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.Border;

/**
 *
 * @author Nilma
 */
public class JFrame_2 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_2
     */
    public JFrame_2() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        Border JPanel_title__Border = BorderFactory.createMatteBorder(7, 7, 7, 7, Color.black);
        jPanel1.setBorder(JPanel_title__Border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_Login = new javax.swing.JButton();
        jButton_Close = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();
        jPassword_Feild_Password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_empty_Username = new javax.swing.JLabel();
        jLabel_empty_password = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loging Fish Farm System");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        jPanel1.setLayout(null);

        jButton_Login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Login.setText("Loging");
        jButton_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Login);
        jButton_Login.setBounds(270, 460, 90, 30);

        jButton_Close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Close.setText("Cancel");
        jButton_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CloseActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Close);
        jButton_Close.setBounds(490, 460, 90, 30);

        jButton_Clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Clear.setText("Clear");
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Clear);
        jButton_Clear.setBounds(40, 460, 90, 30);

        jPassword_Feild_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPassword_Feild_PasswordKeyReleased(evt);
            }
        });
        jPanel1.add(jPassword_Feild_Password);
        jPassword_Feild_Password.setBounds(270, 290, 220, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Password :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 290, 76, 17);

        jTextField_Username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_UsernameKeyReleased(evt);
            }
        });
        jPanel1.add(jTextField_Username);
        jTextField_Username.setBounds(270, 210, 220, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Username: ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 210, 78, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Loging to Fish Farm System");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 50, 630, 30);

        jLabel_empty_Username.setBackground(new java.awt.Color(255, 0, 0));
        jLabel_empty_Username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_empty_Username.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_empty_Username);
        jLabel_empty_Username.setBounds(270, 250, 220, 30);

        jLabel_empty_password.setBackground(new java.awt.Color(255, 0, 0));
        jLabel_empty_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_empty_password.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_empty_password);
        jLabel_empty_password.setBounds(270, 330, 220, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\My Works\\My Java Projects\\Fish_Farm\\Icons\\person-icon.png")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 190, 40, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\My Works\\My Java Projects\\Fish_Farm\\Icons\\password-manager-icon.png")); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 270, 40, 50);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\My Works\\My Java Projects\\Fish_Farm\\Images\\01279_turquise_1920x1080.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 620, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoginActionPerformed
      
        if(jTextField_Username.getText().trim().isEmpty() && jPassword_Feild_Password.getText().trim().isEmpty()){
          
            jLabel_empty_Username.setText("Username is empty!!!");
            jLabel_empty_password.setText("Password is empty!!!");
            getToolkit().beep();
          
        } else if (jTextField_Username.getText().trim().isEmpty()){
       
            jLabel_empty_Username.setText("Username is empty!!!");
            getToolkit().beep();
        
        }else if (jPassword_Feild_Password.getText().trim().isEmpty()){
            
            jLabel_empty_password.setText("Password is empty!!!");
            getToolkit().beep();
        }
                
        String Password = jPassword_Feild_Password.getText();
        String Username = jTextField_Username.getText();
        
        if (Username.contains("Nilma") && (Password.contains("1234"))) {
                       
            
              JFrame_2 f2 = new JFrame_2();
              f2.setVisible(false);//hide
              
              JFrame_3 f3 = new JFrame_3();
              f3.setVisible(true);//hide
        }else{
           
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"Invalied username or password.","Login Faild.",JOptionPane.ERROR_MESSAGE);
           
        } 
               
    }//GEN-LAST:event_jButton_LoginActionPerformed

    private void jTextField_UsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_UsernameKeyReleased
        jLabel_empty_Username.setText(null);
    }//GEN-LAST:event_jTextField_UsernameKeyReleased

    private void jPassword_Feild_PasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassword_Feild_PasswordKeyReleased
        jLabel_empty_password.setText(null);
    }//GEN-LAST:event_jPassword_Feild_PasswordKeyReleased

    private void jButton_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CloseActionPerformed
      
        int a;
        a = JOptionPane.showConfirmDialog(null, "Are you sure to you went to close this program now?", "Close Program", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (a == 0) {
            System.exit(a);
        }
        
    }//GEN-LAST:event_jButton_CloseActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        
        jTextField_Username.setText(null);
        jPassword_Feild_Password.setText(null);
        jLabel_empty_Username.setText(null);
        jLabel_empty_password.setText(null);
        jTextField_Username.grabFocus();
        
    }//GEN-LAST:event_jButton_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;*/
                UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Close;
    private javax.swing.JButton jButton_Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_empty_Username;
    private javax.swing.JLabel jLabel_empty_password;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword_Feild_Password;
    private javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables
}
